CREATE DATABASE IF NOT EXISTS `student_tracker`;
USE `student_tracker`;

DROP TABLE IF EXISTS `students`;

CREATE TABLE `students`(
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`first_name` VARCHAR(30) DEFAULT NULL,
`last_name` VARCHAR(30) DEFAULT NULL,
`email` VARCHAR(30) DEFAULT NULL
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;